version: '3.7'

services:
  web:
    build: .
    container_name: qdrant_demo_web
    ports:
      - 8000:8000
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
    networks:
      - qdrant-net
    volumes:
      - ./data/startups.sqlite3:/code/data/startups.sqlite3
  qdrant:
    image: qdrant/qdrant:v0.10.1
#    mem_limit: 450m
#    ports:
#    - 6333:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

    networks:
      - qdrant-net

networks:
  qdrant-net:
    external:
      name: qdrant-net
